### ISSUE TITLE
Release extensions independently

### ISSUE THREAD

**Issue by sachinraja** [prisma/text-editors#46]
Hey, great work on this text editor, it's amazing!
I am just wondering if it's possible to use the extensions outside the editor and if not, would it be possible to release them separately? I'm trying to add the typescript extension to an editor, but I don't want the React component that bundles all the languages and extensions together.

**Comment by madebysid** [comment]
Hey @sachinraja, that _should_ be possible AFAIK, I can look into that soon and let you know! If possible, then I'm in favour of releasing them separately!

**Comment by sachinraja** [comment]
Thanks! I really appreciate all your work here, it's helped a lot to write my own extensions. Let me know if there's anything I can do to help.

**Comment by madebysid** [comment]
Hey, so having looked into this, it is definitely possible, but it'll introduce some complexity that, quite honestly, isn't worth it for us right now, since the primary consumer of this library is the Data Platform, and we don't have the capacity to do maintain that properly.

If you absolutely do need an extension on its own, your best course of action, in my opinion, would be to fork this repository, and take it from there. Sorry about this!

**Comment by sachinraja** [comment]
That's completely fine. I've copied the extensions into my project and tweaked some things for now (with the LICENSE of course).
